name: Telechargement des logs et dégra & MAJ aeronefs et compos
on:
  schedule: # Planification du workflow selon un planning.
    - cron: '0 0 * * *' # Exécute le script à minuit.
  workflow_dispatch: # Permet de déclencher le workflow manuellement.

jobs:
  download-dataV2:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository # Nom de l'étape
        uses: actions/checkout@v3 # Mettre à jour vers la version v3

      - name: Set up Python
        uses: actions/setup-python@v4 # Mettre à jour vers la version v4
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests

      - name: Run download script
        run: |
          python Script2GithubVers.py # Chemin script degra et log vols

      - name: Run update script
        run: |
          python Script3GithubVers # Chemin script pour aeronefs & compos

      - name: Commit and push data updates
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add data/
          git add aeronefs_2024-06-02.csv
          git add composants_2024-06-02.csv
          git commit -m 'Mise à jour quotidienne des données'
          git push
