name: Telechargement des logs et dégra
on:
  schedule: # Planification du workflow selon un planning.
    - cron: '0 0 * * *' # Exec du script à minuit.
  workflow_dispatch: # Permet de déclencher le workflow manuellement

jobs:
  download-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository # Nom de l'étape
        uses: actions/checkout@v2 # action pour récupérer le dépôt GitHub

      - name: Set up Python
        uses: actions/setup-python@v2 # Configuration de Python
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests

      - name: Run download script
        run: |
          python Script2GithubVers.py # Chemin correct du script

      - name: Commit and push data updates
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add data/
          git commit -m 'Mise à jour quotidienne des données'
          git push
